

export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const GET_MYPROJECTS = 'GET_MYPROJECTS';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const PROJECTS_ERROR = 'PROJECTS_ERROR';
